### DISCUSSION TITLE
Issue with Text Embed Cache Configuration for Fine-Tuning SDXL Model

### DISCUSSION THREAD

**Discussion by Deltadahl** [bghira/SimpleTuner#294] [General]
Thanks for an excellent repo!
I have been struggling to get training to work and would greatly appreciate guidance.
I try to train the XL model but run into the following problem:

```
2024-02-03 11:29:41,556 [INFO] (ArgsParser) VAE Model: madebyollin/sdxl-vae-fp16-fix
2024-02-03 11:29:41,556 [INFO] (ArgsParser) Default VAE Cache location: /store/CIA/scfc3/diffusion/SimpleTuner/models/cache_vae
2024-02-03 11:29:41,556 [INFO] (ArgsParser) Text Cache location: cache
2024-02-03 11:29:41,558 [INFO] (__main__) Distributed environment: DistributedType.NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: bf16

2024-02-03 11:29:41,559 [INFO] (__main__) Enabling tf32 precision boost for NVIDIA devices due to --allow_tf32.
2024-02-03 11:29:41,559 [INFO] (__main__) Load tokenizers
2024-02-03 11:29:42,413 [INFO] (__main__) Load text encoder 1..
2024-02-03 11:29:42,787 [INFO] (__main__) Load text encoder 2..
2024-02-03 11:29:43,833 [INFO] (__main__) Load VAE..
2024-02-03 11:29:44,029 [INFO] (__main__) Moving models to GPU. Almost there.
2024-02-03 11:29:45,221 [INFO] (__main__) Creating the U-net..
2024-02-03 11:29:46,260 [INFO] (__main__) Moving the U-net to GPU.
2024-02-03 11:29:48,072 [INFO] (__main__) Enabling xformers memory-efficient attention.
2024-02-03 11:29:48,271 [INFO] (__main__) Initialising VAE in bf16 precision, you may specify a different value if preferred: bf16, fp16, fp32, default
2024-02-03 11:29:48,338 [INFO] (__main__) Loaded VAE into VRAM.
2024-02-03 11:29:48,358 [INFO] (DataBackendFactory) Configuring text embed backend: alt-embed-cache
2024-02-03 11:29:48,358 [INFO] (TextEmbeddingCache) (Rank: 0) (id=alt-embed-cache) Listing all text embed cache entries
2024-02-03 11:29:48,360 [WARNING] (DataBackendFactory) No default text embed was defined, using alt-embed-cache as the default.
2024-02-03 11:29:48,360 [INFO] (DataBackendFactory) Completed loading text embed services.
2024-02-03 11:29:48,360 [INFO] (DataBackendFactory) Configuring data backend: bloodimage-local
2024-02-03 11:29:48,360 [INFO] (DataBackendFactory) Configured backend: {'id': 'bloodimage-local', 'config': {'vae_cache_clear_each_epoch': True, 'probability': 1.0, 'repeats': 1, 'crop': False, 'crop_aspect': 'square', 'crop_style': 'random', 'resolution': 768, 'resolution_type': 'pixel', 'caption_strategy': 'filename', 'maximum_image_size': None, 'target_downsample_size': None}, 'dataset_type': 'image'}
2024-02-03 11:29:48,360 [INFO] (DataBackendFactory) (id=bloodimage-local) Loading bucket manager.
2024-02-03 11:29:48,361 [INFO] (DataBackendFactory) (id=bloodimage-local) Refreshing aspect buckets.
2024-02-03 11:29:48,361 [INFO] (BucketManager) Discovering new files...
2024-02-03 11:29:48,362 [INFO] (BucketManager) No new files discovered. Doing nothing.
2024-02-03 11:29:48,362 [INFO] (BucketManager) Statistics: {'total_processed': 0, 'skipped': {'already_exists': 4, 'metadata_missing': 0, 'not_found': 0, 'too_small': 0, 'other': 0}}
2024-02-03 11:29:48,363 [INFO] (DataBackendFactory) (id=bloodimage-local) Reloading bucket manager cache.
2024-02-03 11:29:48,363 [INFO] (DataBackendFactory) Configured backend: {'id': 'bloodimage-local', 'config': {'vae_cache_clear_each_epoch': True, 'probability': 1.0, 'repeats': 1, 'crop': False, 'crop_aspect': 'square', 'crop_style': 'random', 'resolution': 768, 'resolution_type': 'pixel', 'caption_strategy': 'filename', 'maximum_image_size': None, 'target_downsample_size': None}, 'dataset_type': 'image', 'data_backend': <helpers.data_backend.local.LocalDataBackend object at 0x7f09cd05a850>, 'instance_data_root': '/store/CIA/scfc3/diffusion/SimpleTuner/TEST_DATA', 'bucket_manager': <helpers.multiaspect.bucket.BucketManager object at 0x7f09e4f80290>}
(Rank: 0)  | Bucket     | Image Count 
------------------------------
(Rank: 0)  | 1.0        | 4           
Loading captions: 100%|█████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 36631.48it/s]
2024-02-03 11:29:48,365 [INFO] (DataBackendFactory) (id=bloodimage-local) Initialise text embed pre-computation using the filename caption strategy. We have 4 captions to process.
2024-02-03 11:29:48,366 [INFO] (DataBackendFactory) (id=bloodimage-local) Completed processing 4 captions.
2024-02-03 11:29:48,366 [INFO] (DataBackendFactory) (id=bloodimage-local) Pre-computing VAE latent space.
2024-02-03 11:29:48,367 [INFO] (DataBackendFactory) Skipping error scan for dataset bloodimage-local. Set 'scan_for_errors' to True in the dataset config to enable this if your training runs into mismatched latent dimensions.
Traceback (most recent call last):
  File "/store/CIA/scfc3/diffusion/SimpleTuner/train_sdxl.py", line 1523, in <module>
    main()
  File "/store/CIA/scfc3/diffusion/SimpleTuner/train_sdxl.py", line 448, in main
    ) = prepare_validation_prompt_list(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/store/CIA/scfc3/diffusion/SimpleTuner/helpers/legacy/validation.py", line 32, in prepare_validation_prompt_list
    raise ValueError(
ValueError: Embed cache engine did not contain a model_type. Cannot continue.
Traceback (most recent call last):
  File "/store/CIA/scfc3/miniconda3/envs/diff_8/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/store/CIA/scfc3/miniconda3/envs/diff_8/lib/python3.11/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/store/CIA/scfc3/miniconda3/envs/diff_8/lib/python3.11/site-packages/accelerate/commands/launch.py", line 979, in launch_command
    simple_launcher(args)
  File "/store/CIA/scfc3/miniconda3/envs/diff_8/lib/python3.11/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/store/CIA/scfc3/miniconda3/envs/diff_8/bin/python', 'train_sdxl.py', '--pretrained_model_name_or_path=stabilityai/stable-diffusion-xl-base-1.0', '--enable_xformers_memory_efficient_attention', '--gradient_checkpointing', '--set_grads_to_none', '--gradient_accumulation_steps=4', '--resume_from_checkpoint=latest', '--snr_gamma=5', '--data_backend_config=/store/CIA/scfc3/diffusion/SimpleTuner/multidatabackend.json', '--num_train_epochs=0', '--max_train_steps=300', '--metadata_update_interval=65', '--learning_rate=8e-7', '--lr_scheduler=constant', '--seed', '420420420', '--lr_warmup_steps=30', '--output_dir=/store/CIA/scfc3/diffusion/SimpleTuner/models', '--inference_scheduler_timestep_spacing=trailing', '--training_scheduler_timestep_spacing=trailing', '--report_to=wandb', '--allow_tf32', '--mixed_precision=bf16', '--vae_dtype=bf16', '--allow_tf32', '--use_8bit_adam', '--use_ema', '--ema_decay=0.999', '--train_batch=1', '--caption_dropout_probability=0.03', '--validation_prompt=a microscope image of a basophil', '--num_validation_images=1', '--validation_num_inference_steps=30', '--validation_seed=42', '--minimum_image_size=768', '--resolution=768', '--validation_resolution=768', '--resolution_type=pixel', '--checkpointing_steps=150', '--checkpoints_total_limit=2', '--validation_steps=100', '--tracker_run_name=simpletuner-sdxl', '--tracker_project_name=sdxl-training', '--validation_guidance=7.5', '--validation_guidance_rescale=0.0', '--validation_negative_prompt=blurry, cropped, ugly']' returned non-zero exit status 1.
```
Initially, I just want to use the file name as the input text to see if I can get things to work. (However, later I want to use the folder name instead of the file name.)
I've put 4 images in a folder called `TEST_DATA` and I use the following `multidatabackend.json`. 

```
[
    {
        "id": "bloodimage-local",
        "type": "local",
        "instance_data_dir": "/store/CIA/scfc3/diffusion/SimpleTuner/TEST_DATA",
        "crop": false,
        "resolution": 768,
        "resolution_type": "pixel",
        "prepend_instance_prompt": true,
        "instance_prompt": "a microscope image of a ",
        "only_instance_prompt": false,
        "caption_strategy": "filename",
        "cache_dir_vae": "vae_cache",
        "vae_cache_clear_each_epoch": true,
        "probability": 1.0,
        "repeats": 1,
        "text_embeds": "alt-embed-cache"
    },
    {
        "id": "alt-embed-cache",
        "dataset_type": "text_embeds",
        "default": false,
        "type": "local",
        "cache_dir": "text_embed_cache"
    }
]
```
I appreciate any guidance you can provide to help get my training started. Thank you!

**Comment by bghira** [comment]
try setting default to true for your text embed cache. it should actually use the sole text embed backend as the default, if none is explicitly defined. so there may be a bug, but as far as i've seen, i remember mine overriding it and warning me that it will do so.

the default text embed backend is required, as it is where the validation prompts are cached and stored - and that is where this process is failing

**Reply by bghira** [reply]
ah, yeah, yours warns too:

> 2024-02-03 11:29:48,360 [WARNING] (DataBackendFactory) No default text embed was defined, using alt-embed-cache as the default.

but it's interesting that this still failed later. hmm

**Comment by bghira** [comment]
```json
[
    {
        "id": "bloodimage-local",
        "type": "local",
        "instance_data_dir": "/store/CIA/scfc3/diffusion/SimpleTuner/TEST_DATA",
        "crop": false,
        "resolution": 768,
        "resolution_type": "pixel",
        "prepend_instance_prompt": true,
        "instance_prompt": "a microscope image of a ",
        "only_instance_prompt": false,
        "caption_strategy": "filename",
        "cache_dir_vae": "vae_cache",
        "vae_cache_clear_each_epoch": true,
        "probability": 1.0,
        "repeats": 1,
        "text_embeds": "alt-embed-cache"
    },
    {
        "id": "alt-embed-cache",
        "dataset_type": "text_embeds",
        "default": true,
        "type": "local",
        "cache_dir": "text_embed_cache"
    }
]
```

try this, it has the one line corrected.

**Comment by Deltadahl** [comment]
Thank you!
However, I have access to two different GPU clusters (don't have sudo) and I get the same error on both of them:
```
Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information

You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```
However, including the suggested lines gives another even longer error message.
Full error message:
```
2024-02-05 15:32:27,887 [INFO] (ArgsParser) VAE Model: madebyollin/sdxl-vae-fp16-fix
2024-02-05 15:32:27,887 [INFO] (ArgsParser) Default VAE Cache location: /home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/diffusion/SimpleTuner/models/cache_vae
2024-02-05 15:32:27,887 [INFO] (ArgsParser) Text Cache location: cache
2024-02-05 15:32:27,889 [INFO] (__main__) Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: bf16

2024-02-05 15:32:27,891 [INFO] (__main__) Enabling tf32 precision boost for NVIDIA devices due to --allow_tf32.
2024-02-05 15:32:27,891 [INFO] (__main__) Load tokenizers
2024-02-05 15:32:28,909 [INFO] (__main__) Load text encoder 1..
2024-02-05 15:32:29,319 [INFO] (__main__) Load text encoder 2..
2024-02-05 15:32:30,573 [INFO] (__main__) Load VAE..
2024-02-05 15:32:30,824 [INFO] (__main__) Moving models to GPU. Almost there.
2024-02-05 15:32:31,375 [INFO] (__main__) Creating the U-net..
2024-02-05 15:32:32,781 [INFO] (__main__) Moving the U-net to GPU.
2024-02-05 15:32:36,228 [INFO] (__main__) Enabling xformers memory-efficient attention.
2024-02-05 15:32:36,524 [INFO] (__main__) Initialising VAE in bf16 precision, you may specify a different value if preferred: bf16, fp16, fp32, default
2024-02-05 15:32:36,644 [INFO] (__main__) Loaded VAE into VRAM.
2024-02-05 15:32:36,708 [INFO] (DataBackendFactory) Configuring text embed backend: alt-embed-cache
2024-02-05 15:32:36,711 [INFO] (TextEmbeddingCache) (Rank: 0) (id=alt-embed-cache) Listing all text embed cache entries
2024-02-05 15:32:36,714 [INFO] (DataBackendFactory) Pre-computing null embedding for caption dropout
2024-02-05 15:32:36,715 [INFO] (DataBackendFactory) Completed loading text embed services.
2024-02-05 15:32:36,715 [INFO] (DataBackendFactory) Configuring data backend: bloodimage-local
2024-02-05 15:32:36,715 [INFO] (DataBackendFactory) Configured backend: {'id': 'bloodimage-local', 'config': {'vae_cache_clear_each_epoch': True, 'probability': 1.0, 'repeats': 1, 'crop': False, 'crop_aspect': 'square', 'crop_style': 'random', 'resolution': 1024, 'resolution_type': 'pixel', 'caption_strategy': 'filename', 'maximum_image_size': None, 'target_downsample_size': None}, 'dataset_type': 'image'}
2024-02-05 15:32:36,717 [INFO] (DataBackendFactory) (id=bloodimage-local) Loading bucket manager.
2024-02-05 15:32:36,718 [INFO] (DataBackendFactory) (id=bloodimage-local) Refreshing aspect buckets.
2024-02-05 15:32:36,718 [INFO] (BucketManager) Discovering new files...
2024-02-05 15:32:36,721 [INFO] (BucketManager) No new files discovered. Doing nothing.
2024-02-05 15:32:36,721 [INFO] (BucketManager) Statistics: {'total_processed': 0, 'skipped': {'already_exists': 12, 'metadata_missing': 0, 'not_found': 0, 'too_small': 0, 'other': 0}}
2024-02-05 15:32:36,722 [INFO] (DataBackendFactory) (id=bloodimage-local) Reloading bucket manager cache.
2024-02-05 15:32:36,723 [INFO] (DataBackendFactory) Configured backend: {'id': 'bloodimage-local', 'config': {'vae_cache_clear_each_epoch': True, 'probability': 1.0, 'repeats': 1, 'crop': False, 'crop_aspect': 'square', 'crop_style': 'random', 'resolution': 1024, 'resolution_type': 'pixel', 'caption_strategy': 'filename', 'maximum_image_size': None, 'target_downsample_size': None}, 'dataset_type': 'image', 'data_backend': <helpers.data_backend.local.LocalDataBackend object at 0x154a275b2d60>, 'instance_data_root': '/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/diffusion/SimpleTuner/TEST_DATA', 'bucket_manager': <helpers.multiaspect.bucket.BucketManager object at 0x154a275b2e20>}
(Rank: 0)  | Bucket     | Image Count 
------------------------------
(Rank: 0)  | 1.0        | 12          
Loading captions: 100%|███████████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 98194.41it/s]
2024-02-05 15:32:36,724 [INFO] (DataBackendFactory) (id=bloodimage-local) Initialise text embed pre-computation using the filename caption strategy. We have 14 captions to process.
2024-02-05 15:32:36,725 [INFO] (DataBackendFactory) (id=bloodimage-local) Completed processing 14 captions.
2024-02-05 15:32:36,725 [INFO] (DataBackendFactory) (id=bloodimage-local) Pre-computing VAE latent space.
2024-02-05 15:32:36,728 [INFO] (DataBackendFactory) Skipping error scan for dataset bloodimage-local. Set 'scan_for_errors' to True in the dataset config to enable this if your training runs into mismatched latent dimensions.
2024-02-05 15:32:41,806 [INFO] (validation) Precomputing the negative prompt embed for validations.
2024-02-05 15:32:46,736 [INFO] (__main__) Unloading text encoders, as they are not being trained.
2024-02-05 15:32:46,855 [INFO] (__main__) After nuking text encoders from orbit, we freed 0.0 GB of VRAM. The real memories were the friends we trained a model on along the way.
2024-02-05 15:32:46,855 [INFO] (__main__) Collected the following data backends: ['alt-embed-cache', 'bloodimage-local']
2024-02-05 15:32:46,855 [INFO] (__main__) Loading constant learning rate scheduler with 3 warmup steps
2024-02-05 15:32:46,859 [INFO] (__main__) Learning rate: 8e-07
2024-02-05 15:32:46,860 [INFO] (__main__) Using AdamW optimizer.
2024-02-05 15:32:46,860 [INFO] (__main__) Optimizer arguments, weight_decay=0.01 eps=1e-08
2024-02-05 15:32:46,867 [INFO] (__main__) Loading our accelerator...
2024-02-05 15:32:47,145 [INFO] (__main__) After removing any undesired samples and updating cache entries, we have settled on 10 epochs and 3 steps per epoch.
2024-02-05 15:32:47,281 [INFO] (__main__) After the VAE from orbit, we freed 0.0 MB of VRAM.
2024-02-05 15:32:47,282 [INFO] (__main__) Checkpoint 'latest' does not exist. Starting a new training run.
2024-02-05 15:32:47,282 [INFO] (MultiAspectSampler-bloodimage-local) (Rank: 0) Multi-aspect sampler statistics:
(Rank: 0)     -> Batch size: 2
(Rank: 0)     -> Seen images: 0
(Rank: 0)     -> Unseen images: 12
(Rank: 0)     -> Current Bucket: None
(Rank: 0)     -> 1 Buckets: ['1.0']
(Rank: 0)     -> 0 Exhausted Buckets: []

wandb: Currently logged in as: simonc (bloodcounts). Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.16.2
wandb: Run data is saved locally in /rds/project/cbs31/rds-cbs31-cmih-covid19/user_files/scfc3_files/diffusion/SimpleTuner/wandb/run-20240205_153249-3faa230b5cc9ef5b58799616dd668c64
wandb: Run `wandb offline` to turn off syncing.
wandb: Resuming run simpletuner-sdxl
wandb: ⭐️ View project at https://wandb.ai/bloodcounts/sdxl-training
wandb: 🚀 View run at https://wandb.ai/bloodcounts/sdxl-training/runs/3faa230b5cc9ef5b58799616dd668c64
2024-02-05 15:32:50,169 [INFO] (__main__) ***** Running training *****
2024-02-05 15:32:50,169 [INFO] (__main__)  -> Num batches = 6
2024-02-05 15:32:50,169 [INFO] (__main__)  -> Num Epochs = 10
2024-02-05 15:32:50,170 [INFO] (__main__)  -> Current Epoch = 1
2024-02-05 15:32:50,170 [INFO] (__main__)  -> Instantaneous batch size per device = 2
2024-02-05 15:32:50,170 [INFO] (__main__)  -> Gradient Accumulation steps = 2
2024-02-05 15:32:50,170 [INFO] (__main__)    -> Total train batch size (w. parallel, distributed & accumulation) = 4
2024-02-05 15:32:50,170 [INFO] (__main__)  -> Total optimization steps = 30
2024-02-05 15:32:50,170 [INFO] (__main__)  -> Total optimization steps remaining = 30
Epoch 1/10, Steps:   0%|                                                                              | 0/30 [00:00<?, ?it/s]cc1: internal compiler error: Illegal instruction
0xb520ff crash_signal
        /tmp/kk562/spack-stage/spack-stage-gcc-11.3.0-4zpip55j2rww33vhy62jl4eliwynqfru/spack-src/gcc/toplev.c:327
0x15b9d9a linemap_line_start(line_maps*, unsigned int, unsigned int)
        /tmp/kk562/spack-stage/spack-stage-gcc-11.3.0-4zpip55j2rww33vhy62jl4eliwynqfru/spack-src/libcpp/line-map.c:771
0x15a9207 _cpp_do_file_change
        /tmp/kk562/spack-stage/spack-stage-gcc-11.3.0-4zpip55j2rww33vhy62jl4eliwynqfru/spack-src/libcpp/directives.c:1152
0x15b0a43 _cpp_stack_file
        /tmp/kk562/spack-stage/spack-stage-gcc-11.3.0-4zpip55j2rww33vhy62jl4eliwynqfru/spack-src/libcpp/files.c:992
0x15b2abd cpp_read_main_file(cpp_reader*, char const*, bool)
        /tmp/kk562/spack-stage/spack-stage-gcc-11.3.0-4zpip55j2rww33vhy62jl4eliwynqfru/spack-src/libcpp/init.c:698
0x6e9606 c_common_post_options(char const**)
        /tmp/kk562/spack-stage/spack-stage-gcc-11.3.0-4zpip55j2rww33vhy62jl4eliwynqfru/spack-src/gcc/c-family/c-opts.c:1139
0x62b66c process_options
        /tmp/kk562/spack-stage/spack-stage-gcc-11.3.0-4zpip55j2rww33vhy62jl4eliwynqfru/spack-src/gcc/toplev.c:1243
0x62b66c do_compile
        /tmp/kk562/spack-stage/spack-stage-gcc-11.3.0-4zpip55j2rww33vhy62jl4eliwynqfru/spack-src/gcc/toplev.c:2123
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://github.com/spack/spack/issues> for instructions.
cc1: internal compiler error: Illegal instruction
0xb520ff crash_signal
        /tmp/kk562/spack-stage/spack-stage-gcc-11.3.0-4zpip55j2rww33vhy62jl4eliwynqfru/spack-src/gcc/toplev.c:327
0x15b9d9a linemap_line_start(line_maps*, unsigned int, unsigned int)
        /tmp/kk562/spack-stage/spack-stage-gcc-11.3.0-4zpip55j2rww33vhy62jl4eliwynqfru/spack-src/libcpp/line-map.c:771
0x15a9207 _cpp_do_file_change
        /tmp/kk562/spack-stage/spack-stage-gcc-11.3.0-4zpip55j2rww33vhy62jl4eliwynqfru/spack-src/libcpp/directives.c:1152
0x15b0a43 _cpp_stack_file
        /tmp/kk562/spack-stage/spack-stage-gcc-11.3.0-4zpip55j2rww33vhy62jl4eliwynqfru/spack-src/libcpp/files.c:992
0x15b2abd cpp_read_main_file(cpp_reader*, char const*, bool)
        /tmp/kk562/spack-stage/spack-stage-gcc-11.3.0-4zpip55j2rww33vhy62jl4eliwynqfru/spack-src/libcpp/init.c:698
0x6e9606 c_common_post_options(char const**)
        /tmp/kk562/spack-stage/spack-stage-gcc-11.3.0-4zpip55j2rww33vhy62jl4eliwynqfru/spack-src/gcc/c-family/c-opts.c:1139
0x62b66c process_options
        /tmp/kk562/spack-stage/spack-stage-gcc-11.3.0-4zpip55j2rww33vhy62jl4eliwynqfru/spack-src/gcc/toplev.c:1243
0x62b66c do_compile
        /tmp/kk562/spack-stage/spack-stage-gcc-11.3.0-4zpip55j2rww33vhy62jl4eliwynqfru/spack-src/gcc/toplev.c:2123
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://github.com/spack/spack/issues> for instructions.
Traceback (most recent call last):
  File "/rds/project/cbs31/rds-cbs31-cmih-covid19/user_files/scfc3_files/diffusion/SimpleTuner/train_sdxl.py", line 1523, in <module>
    main()
  File "/rds/project/cbs31/rds-cbs31-cmih-covid19/user_files/scfc3_files/diffusion/SimpleTuner/train_sdxl.py", line 1151, in main
    model_pred = unet(
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 489, in _fn
    return fn(*args, **kwargs)
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/accelerate/utils/operations.py", line 581, in forward
    return model_forward(*args, **kwargs)
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/accelerate/utils/operations.py", line 569, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/amp/autocast_mode.py", line 16, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/diffusers/models/unet_2d_condition.py", line 1148, in forward
    t_emb = self.get_time_embed(sample=sample, timestep=timestep)
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 655, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 727, in _convert_frame
    result = inner_convert(frame, cache_entry, hooks, frame_state)
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 383, in _convert_frame_assert
    compiled_product = _compile(
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 646, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 562, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
    transformations(instructions, code_options)
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 151, in _fn
    return fn(*args, **kwargs)
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 527, in transform
    tracer.run()
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 2128, in run
    super().run()
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 818, in run
    and self.step()
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 781, in step
    getattr(self, inst.opname)(inst)
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 2243, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 919, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 1087, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 1159, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 1140, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/__init__.py", line 1662, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 1168, in compile_fx
    return aot_autograd(
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/_dynamo/backends/common.py", line 55, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 887, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 600, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 425, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 630, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 97, in aot_dispatch_base
    compiled_fw = compiler(fw_module, updated_flat_args)
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 1100, in fw_compiler_base
    return inner_compile(
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/_dynamo/repro/after_aot.py", line 83, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/_inductor/debug.py", line 305, in inner
    return fn(*args, **kwargs)
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 320, in compile_fx_inner
    compiled_graph = fx_codegen_and_compile(
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 550, in fx_codegen_and_compile
    compiled_fn = graph.compile_to_fn()
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/_inductor/graph.py", line 1116, in compile_to_fn
    return self.compile_to_module().call
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/_inductor/graph.py", line 1070, in compile_to_module
    mod = PyCodeCache.load_by_key_path(
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/_inductor/codecache.py", line 1892, in load_by_key_path
    exec(code, mod.__dict__, mod.__dict__)
  File "/tmp/torchinductor_scfc3/aj/cajicsps3kzboz7w25js5tqd4enj33fmailb74l2tjsnrkpdikc2.py", line 150, in <module>
    async_compile.wait(globals())
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/_inductor/codecache.py", line 2471, in wait
    scope[key] = result.result()
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/torch/_inductor/codecache.py", line 2314, in result
    self.future.result()
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
CalledProcessError: Command '['/usr/local/software/spack/spack-views/rocky8-icelake-20220710/gcc-11.3.0/gcc-11.3.0/4zpip55j2rww33vhy62jl4eliwynqfru/bin/gcc', '/tmp/tmp7gcxfwnj/main.c', '-O3', '-I/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/triton/common/../third_party/cuda/include', '-I/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/include/python3.9', '-I/tmp/tmp7gcxfwnj', '-shared', '-fPIC', '-lcuda', '-o', '/tmp/tmp7gcxfwnj/triton_.cpython-39-x86_64-linux-gnu.so', '-L/lib64', '-L/lib64']' returned non-zero exit status 1.

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

wandb: WARNING Ensure read and write access to run files dir: /rds/project/cbs31/rds-cbs31-cmih-covid19/user_files/scfc3_files/diffusion/SimpleTuner/wandb/run-20240205_153249-3faa230b5cc9ef5b58799616dd668c64/files, control this via the WANDB_DIR env var. See https://docs.wandb.ai/guides/track/environment-variables
wandb: 🚀 View run simpletuner-sdxl at: https://wandb.ai/bloodcounts/sdxl-training/runs/3faa230b5cc9ef5b58799616dd668c64
wandb: Synced 4 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20240205_153249-3faa230b5cc9ef5b58799616dd668c64/logs
Traceback (most recent call last):
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/accelerate/commands/launch.py", line 979, in launch_command
    simple_launcher(args)
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/lib/python3.9/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/envs/diff_3/bin/python', 'train_sdxl.py', '--pretrained_model_name_or_path=stabilityai/stable-diffusion-xl-base-1.0', '--enable_xformers_memory_efficient_attention', '--gradient_checkpointing', '--set_grads_to_none', '--gradient_accumulation_steps=2', '--resume_from_checkpoint=latest', '--snr_gamma=5', '--data_backend_config=/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/diffusion/SimpleTuner/multidatabackend.json', '--num_train_epochs=5', '--max_train_steps=30', '--metadata_update_interval=65', '--learning_rate=8e-7', '--lr_scheduler=constant', '--seed', '420420420', '--lr_warmup_steps=3', '--output_dir=/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/diffusion/SimpleTuner/models', '--inference_scheduler_timestep_spacing=trailing', '--training_scheduler_timestep_spacing=trailing', '--report_to=wandb', '--allow_tf32', '--mixed_precision=bf16', '--vae_dtype=bf16', '--train_batch=2', '--caption_dropout_probability=0.1', '--validation_prompt=ethnographic photography of teddy bear at a picnic', '--num_validation_images=1', '--validation_num_inference_steps=30', '--validation_seed=42', '--minimum_image_size=1024', '--resolution=1024', '--validation_resolution=1024', '--resolution_type=pixel', '--checkpointing_steps=150', '--checkpoints_total_limit=2', '--validation_steps=100', '--tracker_run_name=simpletuner-sdxl', '--tracker_project_name=sdxl-training', '--validation_guidance=7.5', '--validation_guidance_rescale=0.0', '--validation_negative_prompt=blurry, cropped, ugly']' returned non-zero exit status 1.
```

**Reply by bghira** [reply]
see in `sdxl-env.sh` where it says `'inductor'` and change to `'no'`, it seems that some systems aren't set up correctly for torch.compile

**Reply by bghira** [reply]
to be honest, i'm not sure how Spack is involved here. and i never use miniconda, simply poetry and venvs.

**Reply by Deltadahl** [reply]
Thank you!!
It started to train now!!

I had to change both `inductor` -> `no` and install via your `ubuntu.sh` file.

**Comment by Deltadahl** [comment]
Hmm, I want to use a folder structure like this:
- Root_Directory/
  - Folder_1/
    - Subfolder_1/
      - file_1.png
      - file_2.png
      - ...
  - Folder_2/
    - Subfolder_1/
      - file_1.png
      - file_2.png
      - ...

and I want the text input to the model to be:
"a microscope image of" + Subfolder_X name which will be things like "a_basophil", "an_immature_granulocyte" (without `_`).
However, currently, I can only train my model if I have images under Root_Directory. If I put images in a subfolder I get:
```
Exception: Some images were not correctly cached during the VAE Cache operations. Ensure --skip_file_discovery=vae is not set.
```
and I only get cached results under the `vae_cache` folder from `"cache_dir_vae": "vae_cache",` if I have images under the root directory, otherwise `vae_cache` is empty.
Am I doing something wrong or is this a bug?

Full error message (when I have images that are under subfolders)
```
Epoch 1/1 Steps:   0%|                                                                               | 0/300 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/rds/project/cbs31/rds-cbs31-cmih-covid19/user_files/scfc3_files/diffusion/SimpleTuner/train_sdxl.py", line 1523, in <module>
    main()
  File "/rds/project/cbs31/rds-cbs31-cmih-covid19/user_files/scfc3_files/diffusion/SimpleTuner/train_sdxl.py", line 1028, in main
    for step, batch in random_dataloader_iterator(train_backends):
  File "/rds/project/cbs31/rds-cbs31-cmih-covid19/user_files/scfc3_files/diffusion/SimpleTuner/helpers/data_backend/factory.py", line 670, in random_dataloader_iterator
    yield (step, next(chosen_iter))
                 ^^^^^^^^^^^^^^^^^
  File "/rds/project/cbs31/rds-cbs31-cmih-covid19/user_files/scfc3_files/diffusion/SimpleTuner/.venv/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/rds/project/cbs31/rds-cbs31-cmih-covid19/user_files/scfc3_files/diffusion/SimpleTuner/.venv/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 674, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/project/cbs31/rds-cbs31-cmih-covid19/user_files/scfc3_files/diffusion/SimpleTuner/.venv/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/rds/project/cbs31/rds-cbs31-cmih-covid19/user_files/scfc3_files/diffusion/SimpleTuner/helpers/data_backend/factory.py", line 439, in <lambda>
    collate_fn=lambda examples: collate_fn(examples),
                                ^^^^^^^^^^^^^^^^^^^^
  File "/rds/project/cbs31/rds-cbs31-cmih-covid19/user_files/scfc3_files/diffusion/SimpleTuner/helpers/training/collate.py", line 220, in collate_fn
    latent_batch = compute_latents(filepaths, data_backend_id)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/project/cbs31/rds-cbs31-cmih-covid19/user_files/scfc3_files/diffusion/SimpleTuner/helpers/training/collate.py", line 88, in compute_latents
    latents = list(
              ^^^^^
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/lib/python3.11/concurrent/futures/_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/lib/python3.11/concurrent/futures/_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/miniconda3/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/project/cbs31/rds-cbs31-cmih-covid19/user_files/scfc3_files/diffusion/SimpleTuner/helpers/training/collate.py", line 77, in fetch_latent
    latent = StateTracker.get_vaecache(id=data_backend_id).retrieve_from_cache(fp)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/project/cbs31/rds-cbs31-cmih-covid19/user_files/scfc3_files/diffusion/SimpleTuner/helpers/caching/vae.py", line 129, in retrieve_from_cache
    return self.encode_images([None], [filepath])[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/project/cbs31/rds-cbs31-cmih-covid19/user_files/scfc3_files/diffusion/SimpleTuner/helpers/caching/vae.py", line 366, in encode_images
    raise Exception(
Exception: Some images were not correctly cached during the VAE Cache operations. Ensure --skip_file_discovery=vae is not set.
Problematic images: ['/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/diffusion/SimpleTuner/TEST_DATA/Basophil/20190531_120229_0.jpg']
wandb: WARNING Ensure read and write access to run files dir: /rds/project/cbs31/rds-cbs31-cmih-covid19/user_files/scfc3_files/diffusion/SimpleTuner/wandb/run-20240205_184617-e6360e076d282be65180d0d09d3964e4/files, control this via the WANDB_DIR env var. See https://docs.wandb.ai/guides/track/environment-variables
wandb: 🚀 View run simpletuner-sdxl at: https://wandb.ai/bloodcounts/sdxl-training/runs/e6360e076d282be65180d0d09d3964e4
wandb: Synced 4 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20240205_184617-e6360e076d282be65180d0d09d3964e4/logs
Traceback (most recent call last):
  File "/rds/project/cbs31/rds-cbs31-cmih-covid19/user_files/scfc3_files/diffusion/SimpleTuner/.venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/rds/project/cbs31/rds-cbs31-cmih-covid19/user_files/scfc3_files/diffusion/SimpleTuner/.venv/lib/python3.11/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/rds/project/cbs31/rds-cbs31-cmih-covid19/user_files/scfc3_files/diffusion/SimpleTuner/.venv/lib/python3.11/site-packages/accelerate/commands/launch.py", line 979, in launch_command
    simple_launcher(args)
  File "/rds/project/cbs31/rds-cbs31-cmih-covid19/user_files/scfc3_files/diffusion/SimpleTuner/.venv/lib/python3.11/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/rds/project/cbs31/rds-cbs31-cmih-covid19/user_files/scfc3_files/diffusion/SimpleTuner/.venv/bin/python', 'train_sdxl.py', '--pretrained_model_name_or_path=stabilityai/stable-diffusion-xl-base-1.0', '--enable_xformers_memory_efficient_attention', '--gradient_checkpointing', '--set_grads_to_none', '--gradient_accumulation_steps=2', '--resume_from_checkpoint=latest', '--snr_gamma=5', '--data_backend_config=/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/diffusion/SimpleTuner/multidatabackend.json', '--num_train_epochs=10', '--max_train_steps=300', '--metadata_update_interval=65', '--learning_rate=8e-7', '--lr_scheduler=constant', '--seed', '420420420', '--lr_warmup_steps=30', '--output_dir=/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/diffusion/SimpleTuner/models', '--inference_scheduler_timestep_spacing=trailing', '--training_scheduler_timestep_spacing=trailing', '--report_to=wandb', '--allow_tf32', '--mixed_precision=bf16', '--vae_dtype=bf16', '--train_batch=2', '--caption_dropout_probability=0.1', '--validation_prompt=ethnographic photography of teddy bear at a picnic', '--num_validation_images=1', '--validation_num_inference_steps=30', '--validation_seed=42', '--minimum_image_size=768', '--resolution=768', '--validation_resolution=768', '--resolution_type=pixel', '--checkpointing_steps=150', '--checkpoints_total_limit=2', '--validation_steps=100', '--tracker_run_name=simpletuner-sdxl', '--tracker_project_name=sdxl-training', '--validation_guidance=7.5', '--validation_guidance_rescale=0.0', '--validation_negative_prompt=blurry, cropped, ugly']' returned non-zero exit status 1.
```

**Reply by bghira** [reply]
hmm, it seems there is indeed an issue with subfolders. as a workaround until i can look deeper into this, you can add a `multidatabackend.json` entry for each subfolder. that's not ideal.. but it'll take possibly a day or two to resolve the issue, including the setup to reproduce the issue.

i (only) really train via Cloudflare R2 (S3) these days, so unfortunately the local data backend support sometimes misses fixes like these.

**Reply by bghira** [reply]
i've pushed a tentative resolution to the main branch. if you could try that, let me know. i gave it a whirl and it worked to cache the embeds for the subfolders, but i didn't go further than trying to step the components forward, which OOM'd on the machine

**Reply by bghira** [reply]
for a bit more background, the historic means of data was to train just from a big glob of photos. only recently did i add in support for S3 prefixes, so that the SD 2.x VAE embeds do not clash with the SDXL VAE embeds.

making the folders a piece of the caption is likely a fair bit trickier. will have to think on it

**Reply by Deltadahl** [reply]
I just pulled the new code and it seems to work (with subfolders).

However, when I use a "normal" folder structure like this
- Root_Directory/
        - file_1.png
        - file_2.png
...
I get the following error:
```
2024-02-06 06:31:58,508 [INFO] (ArgsParser) VAE Model: madebyollin/sdxl-vae-fp16-fix
2024-02-06 06:31:58,508 [INFO] (ArgsParser) Default VAE Cache location: /home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/diffusion/SimpleTuner/models/cache_vae
2024-02-06 06:31:58,508 [INFO] (ArgsParser) Text Cache location: cache
2024-02-06 06:31:58,510 [INFO] (__main__) Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: bf16

2024-02-06 06:31:58,511 [INFO] (__main__) Enabling tf32 precision boost for NVIDIA devices due to --allow_tf32.
2024-02-06 06:31:58,511 [INFO] (__main__) Load tokenizers
2024-02-06 06:31:59,712 [INFO] (__main__) Load text encoder 1..
2024-02-06 06:32:00,313 [INFO] (__main__) Load text encoder 2..
2024-02-06 06:32:01,518 [INFO] (__main__) Load VAE..
2024-02-06 06:32:01,750 [INFO] (__main__) Moving models to GPU. Almost there.
2024-02-06 06:32:02,301 [INFO] (__main__) Creating the U-net..
2024-02-06 06:32:03,677 [INFO] (__main__) Moving the U-net to GPU.
2024-02-06 06:32:06,980 [INFO] (__main__) Enabling xformers memory-efficient attention.
2024-02-06 06:32:07,253 [INFO] (__main__) Initialising VAE in bf16 precision, you may specify a different value if preferred: bf16, fp16, fp32, default
2024-02-06 06:32:07,366 [INFO] (__main__) Loaded VAE into VRAM.
2024-02-06 06:32:07,429 [INFO] (DataBackendFactory) Configuring text embed backend: alt-embed-cache
2024-02-06 06:32:07,432 [INFO] (TextEmbeddingCache) (Rank: 0) (id=alt-embed-cache) Listing all text embed cache entries
2024-02-06 06:32:07,435 [INFO] (DataBackendFactory) Pre-computing null embedding for caption dropout
2024-02-06 06:32:12,458 [INFO] (DataBackendFactory) Completed loading text embed services.                                   
2024-02-06 06:32:12,458 [INFO] (DataBackendFactory) Configuring data backend: bloodimage-local
2024-02-06 06:32:12,458 [INFO] (DataBackendFactory) Configured backend: {'id': 'bloodimage-local', 'config': {'vae_cache_clear_each_epoch': True, 'probability': 1.0, 'repeats': 1, 'crop': False, 'crop_aspect': 'square', 'crop_style': 'random', 'resolution': 768, 'resolution_type': 'pixel', 'caption_strategy': 'filename', 'maximum_image_size': None, 'target_downsample_size': None}, 'dataset_type': 'image'}
2024-02-06 06:32:12,461 [INFO] (DataBackendFactory) (id=bloodimage-local) Loading bucket manager.
2024-02-06 06:32:12,461 [INFO] (DataBackendFactory) (id=bloodimage-local) Refreshing aspect buckets.
Generating aspect bucket cache:  67%|██████████████████▉         | 143/212 [00:01<00:00, 152.04it/s]2024-02-06 06:32:13,686 [ERROR] (MultiaspectImage) Error processing image: image file is truncated
Generating aspect bucket cache:  75%|█████████████████████▏      | 160/212 [00:01<00:00, 154.57it/s]2024-02-06 06:32:13,738 [ERROR] (MultiaspectImage) image file is truncated
2024-02-06 06:32:14,028 [INFO] (DataBackendFactory) (id=bloodimage-local) Reloading bucket manager cache.
2024-02-06 06:32:14,029 [INFO] (DataBackendFactory) Configured backend: {'id': 'bloodimage-local', 'config': {'vae_cache_clear_each_epoch': True, 'probability': 1.0, 'repeats': 1, 'crop': False, 'crop_aspect': 'square', 'crop_style': 'random', 'resolution': 768, 'resolution_type': 'pixel', 'caption_strategy': 'filename', 'maximum_image_size': None, 'target_downsample_size': None}, 'dataset_type': 'image', 'data_backend': <helpers.data_backend.local.LocalDataBackend object at 0x14e10e4535e0>, 'instance_data_root': '/home/scfc3/rds/rds-cbs31-cmih-covid19/user_files/scfc3_files/diffusion/SimpleTuner/TEST_DATA/Basophil', 'bucket_manager': <helpers.multiaspect.bucket.BucketManager object at 0x14e10e465a90>}
(Rank: 0)  | Bucket     | Image Count 
------------------------------
(Rank: 0)  | 1.0        | 132         
Loading captions: 100%|████████████████████████████████████████████████████████████████| 212/212 [00:00<00:00, 147755.47it/s]
2024-02-06 06:32:14,032 [INFO] (DataBackendFactory) (id=bloodimage-local) Initialise text embed pre-computation using the filename caption strategy. We have 212 captions to process.
2024-02-06 06:32:22,656 [INFO] (DataBackendFactory) (id=bloodimage-local) Completed processing 212 captions.                 
2024-02-06 06:32:22,656 [INFO] (DataBackendFactory) (id=bloodimage-local) Pre-computing VAE latent space.
2024-02-06 06:32:22,660 [INFO] (DataBackendFactory) Skipping error scan for dataset bloodimage-local. Set 'scan_for_errors' to True in the dataset config to enable this if your training runs into mismatched latent dimensions.
2024-02-06 06:32:22,662 [ERROR] (__main__) string index out of range, traceback: Traceback (most recent call last):          
  File "/rds/project/cbs31/rds-cbs31-cmih-covid19/user_files/scfc3_files/diffusion/SimpleTuner/train_sdxl.py", line 428, in main
    configure_multi_databackend(
  File "/rds/project/cbs31/rds-cbs31-cmih-covid19/user_files/scfc3_files/diffusion/SimpleTuner/helpers/data_backend/factory.py", line 542, in configure_multi_databackend
    init_backend["vaecache"].process_buckets()
  File "/rds/project/cbs31/rds-cbs31-cmih-covid19/user_files/scfc3_files/diffusion/SimpleTuner/helpers/caching/vae.py", line 616, in process_buckets
    ) = self._image_filename_from_vaecache_filename(filepath)
  File "/rds/project/cbs31/rds-cbs31-cmih-covid19/user_files/scfc3_files/diffusion/SimpleTuner/helpers/caching/vae.py", line 98, in _image_filename_from_vaecache_filename
    generated_names = self.generate_vae_cache_filename(filepath)
  File "/rds/project/cbs31/rds-cbs31-cmih-covid19/user_files/scfc3_files/diffusion/SimpleTuner/helpers/caching/vae.py", line 91, in generate_vae_cache_filename
    if subfolders[0] == "/":
IndexError: string index out of range
```

**Reply by Deltadahl** [reply]
Also, the lr wandb end the tqdm bar says I have do not correspond to the lr I try to use:
```
wandb: Run summary:
wandb:             epoch 1
wandb:     learning_rate 0.001
wandb: optimization_loss 1.00959
wandb:        train_loss 1.0163
wandb:   train_luminance 179.97301
```
```
Epoch 1/1, Steps:   7%|███▏                                       | 22/300 [03:06<39:15,  8.47s/it, lr=0.001, step_loss=1.01]
```
But the info says:
```
2024-02-06 06:43:02,882 [INFO] (__main__) Learning rate: 8e-07
```
and I use
```
export LEARNING_RATE=8e-7 #@param {type:"number"}
```
However, I don't know if this was the case before the new push or not, but I assume it was because my loss was around 1 then as well.

**Reply by bghira** [reply]
i've popped a check in to the main branch for the subfolders element length.

i had a bunch of other changes in another branch for the subfolder name prepending to the caption, and it is indeed as tricky to implement as i thought. i'm not sure that one will happen

**Reply by bghira** [reply]
which LR scheduler are you using?

**Reply by bghira** [reply]
ah, nvm. i see 'constant' with 3 warmup steps. not sure why the LR is so high there :thinking:

**Reply by bghira** [reply]
i assume you use Adafactor optimizer, which is pretty complicated and can be set up in multiple ways. SimpleTuner only has one means of it implemented, which is using relative_step and auto-optimizing the learning rate. there's another which is to use it as a drop-in for AdamW but that didn't seem to work very well in testing.

i'm not sure why the loss value is so high, but maybe the learning rate can be retrieved more accurately.

**Comment by bghira** [comment]
well since it seems the original issue is resolved and i'm not clear on the settings or remaining problems, please open an issue report with some new logs and your complete `train_sdxl.py` commandline settings :)
