### ISSUE TITLE
train_dataloaders[0] IndexError: list index out of range

### ISSUE THREAD

**Issue by BuildBackBuehler** [bghira/SimpleTuner#343]
I've gotten this in a million billion different configurations. Though I am already 99% certain where the issue is, just hoping to get help with narrowing it down to the issue in my backend_data_loader_config file. 

`2024-04-05 20:20:59,607 [WARNING] (xformers) WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.4.0.dev20240401 with CUDA None (you have 2.2.2)
    Python  3.11.7 (you have 3.11.7)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
2024-04-05 20:21:03,785 [INFO] (ArgsParser) VAE Model: madebyollin/sdxl-vae-fp16-fix
2024-04-05 20:21:03,785 [INFO] (ArgsParser) Default VAE Cache location: /Users/zack/.home/gitrepos/comfyui/models/loras/OnlyThots/cache_vae
2024-04-05 20:21:03,785 [INFO] (ArgsParser) Text Cache location: cache
2024-04-05 20:21:03,785 [INFO] (ArgsParser) It seems that --validation_resolution was given in megapixels (1.1). Converting to pixel measurement: 1096px
2024-04-05 20:21:03,790 [INFO] (__main__) Load tokenizers
2024-04-05 20:21:03,902 [INFO] (__main__) Load text encoder 1..
2024-04-05 20:21:04,645 [INFO] (__main__) Load text encoder 2..
2024-04-05 20:21:08,986 [INFO] (__main__) Load VAE..
2024-04-05 20:21:09,198 [INFO] (__main__) Moving models to GPU. Almost there.
2024-04-05 20:21:09,702 [INFO] (__main__) Creating the U-net..
2024-04-05 20:21:11,800 [INFO] (__main__) Moving the U-net to GPU in torch.float32 precision.
2024-04-05 20:21:13,626 [INFO] (__main__) Using LoRA training mode.
2024-04-05 20:21:13,631 [INFO] (__main__) Adding LoRA adapter to the unet model..
2024-04-05 20:21:14,496 [INFO] (__main__) Initialising VAE in fp32 precision, you may specify a different value if preferred: bf16, fp16, fp32, default
2024-04-05 20:21:14,639 [INFO] (__main__) Loaded VAE into VRAM.
2024-04-05 20:21:14,646 [INFO] (DataBackendFactory) Configuring text embed backend: main_Florence
2024-04-05 20:21:14,647 [INFO] (TextEmbeddingCache) (Rank: 0) (id=main_Florence) Listing all text embed cache entries
2024-04-05 20:21:14,647 [INFO] (DataBackendFactory) Pre-computing null embedding for caption dropout
2024-04-05 20:21:14,647 [INFO] (DataBackendFactory) Completed loading text embed services.
2024-04-05 20:21:15,134 [INFO] (validation) Precomputing the negative prompt embed for validations.
2024-04-05 20:21:15,307 [INFO] (__main__) Moving text encoders back to CPU, to save VRAM.
2024-04-05 20:21:15,838 [INFO] (__main__) After nuking text encoders from orbit, we freed 0.0 GB of VRAM. The real memories were the friends we trained a model on along the way.
2024-04-05 20:21:15,838 [INFO] (__main__) Collected the following data backends: ['main_Florence']
2024-04-05 20:21:15,838 [INFO] (__main__) Loading constant_with_warmup learning rate scheduler with 69 warmup steps
2024-04-05 20:21:15,851 [INFO] (__main__) Learning rate: 1.0
2024-04-05 20:21:15,852 [INFO] (__main__) Using Prodigy optimizer. Experimental.
2024-04-05 20:21:15,862 [INFO] (__main__) Optimizer arguments, weight_decay=0.01 eps=1e-08, extra_arguments={'weight_decay': 0.01, 'eps': 1e-08, 'lr': 1.0, 'betas': (0.9, 0.999), 'beta3': None, 'decouple': True, 'use_bias_correction': True, 'safeguard_warmup': True, 'd_coef': 0.5}
2024-04-05 20:21:15,862 [INFO] (__main__) Using generic 'constant_with_warmup' learning rate scheduler.
2024-04-05 20:21:15,862 [INFO] (__main__) Using EMA. Creating EMAModel.
2024-04-05 20:21:15,963 [INFO] (__main__) EMA model creation complete.
2024-04-05 20:21:15,965 [INFO] (__main__) Loading our accelerator...`

[datasetconfig.json](https://github.com/bghira/SimpleTuner/files/14891808/datasetconfig.json)

**Comment by BuildBackBuehler** [comment]
So what I mean is I tried directly applying my arguments to train_sdxl.py originally, then moved over to using sdxl-env.sh, push it thru train_sdxl.sh. As you may imagine, my arguments should be crispy clean. Only real variable that I haven't messed with is the backend config and all the data/vars in there. 

<img width="577" alt="image" src="https://github.com/bghira/SimpleTuner/assets/116780517/a184ff05-52ce-4974-88d6-8dd0f47346aa">

<img width="660" alt="image" src="https://github.com/bghira/SimpleTuner/assets/116780517/1e686a25-5695-4154-a3ab-24b1f7f7713c">

One thought of mine is...maybe using the databackend.json as the DATA_LOADER_CONFIG target? As to say instead it should be...

DATA_LOADER_CONFIG = '/Path/to/the/directory'  (leaving out databackend.json) the other is I just janked up datasetconfig.json inside lol. ALso wasn't sure if my overflow photobucket should get its own config as dataset 2 (as is the case in my config) or if there were setting choices I wasn't aware of to set it up within dataset 1's config.

**Comment by bghira** [comment]
this is kind of a lot to take in and i'm very confused.

i would recommend resetting to git master branch and then using `adamw_bf16` optimizer and `bf16` everywhere

lora rank 512 tho? what's happening here?

**Comment by BuildBackBuehler** [comment]
Heh yeah, I wanted to be...comprehensive. Also wrote it burnt out & sleep deprived of course!

As far as the 512 rank, I don't know crap about crap and I may have misread some "best settings" articles (or out-of-date, SD1.5-centric, etc.). But I saw higher rank = better LoRA and 2:1 with alpha. 

But the point of failure -- train_dataloaders[0]...isn't something related to my Data Backend config file(included @ bottom of the OP dataconfig.json)? I figured it had to be. Though having looked @ the train_sdxl.py, it did *seem* like that index int. increases w/ config choices so perhaps it is just my general loadout/accel. config. 

I was under the impression I needed to use FP32, FP16 pure for Metal/MPS(?).

**Comment by BuildBackBuehler** [comment]
Been tinkering with this like crazy and 0 luck. 

I have a feeling it is because my data isn't up-to-snuff. I thought I could get away with a directory with some images (all .png) and an accompanying .txt file of the same name for each image. This was originally within 1 directory. I have since separated 'em into an image & a text dir. 

On top of that, I have a secondary directory -- strictly images (the "alt" ID'd dataset entry in my config.json)

So I have been experimenting and ended up with the atrocity below. The aforementioned directory w/ the caption .txt files is serving as the "text embed" dir. which I suspect is the root of my issues. I would've figured the combined directory serving as 1 of the 2 dataset entries sufficed but it gave me an error about setting a default text_embed dir.

I call it an atrocity because I must've plugged in and pulled out all of the settings, esp. cache-related terms, a dozen times. Unsure if cache_dir could be in the same as dir. as "text_embeds" (text_embed_cache) and if I needed to explicitly name a path for each. May seem kinda random, but when I updated SimpTune I was met with new errors. Like how the text_embed_cache didn't contain the "model_type" and who knows what else. 

Just scratched the surface with dropping Prodigy for adam_bfloat16, didn't tinker w/ its settings but dropping it in I still ended up with the list index out of range error.

**Comment by bghira** [comment]
have you seen [the dataloader config doc](https://github.com/bghira/SimpleTuner/blob/main/documentation/DATALOADER.md)?

**Comment by BuildBackBuehler** [comment]
> * all of the image and text files need to be in the same dir, or, rename the image files to have their caption as their name, and use `filename` caption_strategy
> * the text_embeds dataset is about storing text encoder outputs, it is not where the text files go
> * be sure to install the latest pytorch dependencies on apple `poetry -C install/apple install` and use bf16
> 
> or follow the [dreambooth guide](https://github.com/bghira/SimpleTuner/blob/main/documentation/DREAMBOOTH.md) if you are trying to train in a single subject

Ohhhhhh. That's quite the revelation for me 🥴 (@ point #2)! I'll give another go @ fixing up the dataset_loader and see what happens with this elucidating info and/or copy-pasta everything into the filename of the images, seems like the safest bet. 

I fixed up my (v)env, but that didn't produce any change. I'm using Torch 2.4.0dev and most of the key packages are the newest releases. I do have a few, like Diffusers from Beinzeisii's fork, oddities. 

I actually had intended to use Dreambooth originally, it is 100% more up my alley, only intending on doing single subjects for now. I guess I just got so caught up in the most run-of-the-mill/well documented path provided (and I have read over all the docs 3-4x, including DB's). 

And OT...or maybe a workaround. I have a rig running Manjaro w/ my RTX3070 + Tesla M40. It was seemingly running fine outside of the mem. issue. -- I figure there must be a decent way to jerryrig my rig to run a DB instance if I set the Tesla M40 as the primary GPU. Seems Torch has a lot of optimizations for multi-GPU MLing these days. I'd run it headless regardless, but have you tried to do distributed network training with an MPS device in the mix? If it is possible, no clue what a sensible way would be to divy up the training. 

Sorry for all the rambling, no sleep will do that. But I appreciate your help thus far more than you could ever imagine! Its been a tough 1-2 yrs diving into ML/Coding sans support and armed with...Python101 uni. prior experience 😂

**Comment by BuildBackBuehler** [comment]
So switching to filename-based captioning was semi-successful. Just bc this is open, vs. the thread just recently closed with respect to the error I am now running into, I'll post about it here. 

```
> accelerate launch simpletuner/train_sdxl.py --vae_batch_size 5 --train_batch 5 --model_type "lora" --pretrained_model_name_or_path /Users/zack/.home/gitrepos/ComfyUI/input/SEX --data_backend_config /Users/zack/.home/gitrepos/ComfyUI/SimpleTuner/build/ffs/datasetconfigcopy.json --gradient_accumulation_steps 3 --num_train_epochs 5 --max_train_steps 1200  --learning_rate 1.0 --lr_scheduler 'constant_with_warmup' --seed 837420 --lr_warmup_steps 69 --output_dir /Users/zack/.home/gitrepos/comfyui/models/loras/OnlyThots --inference_scheduler_timestep_spacing 'trailing' --training_scheduler_timestep_spacing 'trailing'   --caption_dropout_probability 0.1 --validation_prompt 'Scandalous papparazzi photo of the most beautiful woman: Florence Pugh' --num_validation_images 10 --validation_num_inference_steps 30 --validation_resolution 1.1  --resolution_type 'area' --checkpointing_steps 1200 --checkpoints_total_limit 1 --validation_steps 100 --tracker_run_name 'NOFUN' --tracker_project_name 'TRAININGFML' --validation_guidance 7.5 --validation_guidance_rescale 0.7 --validation_seed 110769 --validation_negative_prompt 'ugly, bald, fat man. Blurry. Anime drawing.' --logging_dir /Users/zack/.home/gitrepos/comfyui/wandb --report_to "wandb" --cache_dir_text /Users/zack/.home/gitrepos/ComfyUI/SimpleTuner/build/ffs/cache_house/text --lora_rank 128 --lora_alpha 32 --timestep_bias_strategy 'later' --timestep_bias_portion 0.2 --timestep_bias_multiplier 3 --snr_gamma 5 --use_ema --ema_decay 0.9995 --prodigy_use_bias_correction 1 --prodigy_safeguard_warmup 1 --prodigy_weight_decay 0.01 --adam_beta1 0.9 --adam_beta2 0.99 --use_prodigy_optimizer --lr_scale --gradient_checkpointing --validation_torch_compile 1 --unet_attention_slice --i_know_what_i_am_doing --cache_clear_validation_prompts --aspect_bucket_worker_count 10 --debug_aspect_buckets --debug_dataset_loader --adam_bfloat16   --rescale_betas_zero_snr
in oss file
in oss file
False
'NoneType' object has no attribute 'cadam32bit_grad_fp32'
2024-04-12 03:00:34,680 [INFO] (ArgsParser) VAE Model: madebyollin/sdxl-vae-fp16-fix
2024-04-12 03:00:34,681 [INFO] (ArgsParser) Default VAE Cache location: /Users/zack/.home/gitrepos/comfyui/models/loras/OnlyThots/cache_vae
2024-04-12 03:00:34,681 [INFO] (ArgsParser) Text Cache location: /Users/zack/.home/gitrepos/ComfyUI/SimpleTuner/build/ffs/cache_house/text
2024-04-12 03:00:34,681 [INFO] (ArgsParser) It seems that --validation_resolution was given in megapixels (1.1). Converting to pixel measurement: 1096px
2024-04-12 03:00:34,684 [INFO] (__main__) Scaling learning rate (1.0), due to --lr_scale
2024-04-12 03:00:34,684 [INFO] (__main__) Load tokenizers
2024-04-12 03:00:34,755 [INFO] (__main__) Load text encoder 1..
2024-04-12 03:00:34,874 [INFO] (__main__) Load text encoder 2..
2024-04-12 03:00:35,496 [INFO] (__main__) Load VAE..
2024-04-12 03:00:35,642 [INFO] (__main__) Moving models to GPU. Almost there.
2024-04-12 03:00:36,716 [INFO] (__main__) Creating the U-net..
2024-04-12 03:00:38,569 [INFO] (__main__) Moving the U-net to GPU in torch.bfloat16 precision.
2024-04-12 03:00:42,092 [INFO] (__main__) Using LoRA training mode.
2024-04-12 03:00:42,097 [INFO] (__main__) Adding LoRA adapter to the unet model..
2024-04-12 03:00:44,673 [INFO] (__main__) Initialising VAE in bf16 precision, you may specify a different value if preferred: bf16, fp32, default
2024-04-12 03:00:44,941 [INFO] (__main__) Loaded VAE into VRAM.
2024-04-12 03:00:44,959 [INFO] (DataBackendFactory) Configuring text embed backend: textembeds
2024-04-12 03:00:44,960 [INFO] (TextEmbeddingCache) (Rank: 0) (id=textembeds) Listing all text embed cache entries
2024-04-12 03:00:44,960 [INFO] (DataBackendFactory) Pre-computing null embedding for caption dropout
2024-04-12 03:00:44,960 [INFO] (DataBackendFactory) Completed loading text embed services.
2024-04-12 03:00:44,960 [INFO] (DataBackendFactory) Configuring data backend: main
2024-04-12 03:00:44,960 [INFO] (DataBackendFactory) Configured backend: {'id': 'main', 'config': {'vae_cache_clear_each_epoch': True, 'repeats': 10, 'crop': False, 'crop_aspect': 'preserve', 'crop_style': 'random', 'resolution': 1.03, 'resolution_type': 'area', 'caption_strategy': 'filename', 'maximum_image_size': None, 'target_downsample_size': 1.25}, 'dataset_type': 'image'}
2024-04-12 03:00:44,960 [INFO] (DataBackendFactory) (id=main) Loading bucket manager.
2024-04-12 03:00:44,962 [INFO] (JsonMetadataBackend) Checking for cache file: /Users/zack/.home/gitrepos/ComfyUI/SimpleTuner/build/FFS/please/aspect_ratio_bucket_indices.json
2024-04-12 03:00:44,962 [WARNING] (JsonMetadataBackend) No cache file found, creating new one.
2024-04-12 03:00:44,962 [INFO] (DataBackendFactory) (id=main) Refreshing aspect buckets on main process.
2024-04-12 03:00:44,962 [INFO] (BaseMetadataBackend) Discovering new files...
2024-04-12 03:00:44,963 [INFO] (BaseMetadataBackend) Compressed 0 existing files from 0.
2024-04-12 03:00:45,075 [INFO] (BaseMetadataBackend) Image processing statistics: {'total_processed': 8, 'skipped': {'already_exists': 0, 'metadata_missing': 0, 'not_found': 0, 'too_small': 0, 'other': 0}}
2024-04-12 03:00:45,075 [INFO] (BaseMetadataBackend) Completed aspect bucket update.
2024-04-12 03:00:45,076 [INFO] (DataBackendFactory) Configured backend: {'id': 'main', 'config': {'vae_cache_clear_each_epoch': True, 'repeats': 10, 'crop': False, 'crop_aspect': 'preserve', 'crop_style': 'random', 'resolution': 1.03, 'resolution_type': 'area', 'caption_strategy': 'filename', 'maximum_image_size': None, 'target_downsample_size': 1.25}, 'dataset_type': 'image', 'data_backend': <helpers.data_backend.local.LocalDataBackend object at 0x3129fdb50>, 'instance_data_root': '/Users/zack/.home/gitrepos/ComfyUI/SimpleTuner/build/FFS/please', 'metadata_backend': <helpers.metadata.backends.json.JsonMetadataBackend object at 0x321f3e210>}
(Rank: 0)  | Bucket     | Image Count
------------------------------
(Rank: 0)  | 0.571      | 0
2024-04-12 03:00:45,076 [ERROR] (__main__) No images were discovered by the bucket manager in the dataset: main., traceback: Traceback (most recent call last):
  File "/Users/zack/.home/gitrepos/ComfyUI/simpletuner/train_sdxl.py", line 428, in main
    configure_multi_databackend(
  File "/Users/zack/.home/gitrepos/ComfyUI/SimpleTuner/helpers/data_backend/factory.py", line 511, in configure_multi_databackend
    raise Exception(
Exception: No images were discovered by the bucket manager in the dataset: main.
```

I've ran it in a million, billion different ways under the sun and nothin' will run. 1 thing I probably did not try enough of has been swapping Prodigy out. I think whilst reading it led me to believe Prodigy *should* work in 16-bit and that 'adam_bfloat16' arg signifies Pure_BF16, as opposed to an Adam16 optimizer. I'd say it was a 50/50 on using that arg in any case. I also made sure that I had every package that was incl. in the Poetry.lock file. 

I was able to trigger the other bug, with this setup, so I have to wonder if the errors are related/share the same origin. In the other thread I'd also mentioned a 3rd error. One that was resolved with the update made 12-18 hours ago. It was an issue with Multiaspect/Image.py and converting the resolution that was input (bc as an arg. its taken as a string) when it needed to be converted to a float value before it could be * 1e6 or 1e3...sorry but a little fuzzy there, see other thread for more. 

I also thought this was kinda strange, at least I don't know what the :false is supposed to signify. And I only recently saw these were being created -- in my output dir. (would figure they'd end up in my cache dirs.)
Moreso odd because I donno what the "false" signifies for each photo. There was also a caption file that has been created there that's always completely empty. I imagine that may be the key to the mystery (all_caption_files.json)

[all_image_files_main.json](https://github.com/bghira/SimpleTuner/files/14955345/all_image_files_main.json)
[all_text_cache_files_textembeds.json](https://github.com/bghira/SimpleTuner/files/14955346/all_text_cache_files_textembeds.json)

**Comment by bghira** [comment]
do me a favour and just train on a standardised dataset, https://huggingface.co/datasets/ptx0/pseudo-camera-10k

please reset all code to the master branch and just use a basic config. there should be no need to alter the code for float errors or anything like that.

**Comment by BuildBackBuehler** [comment]
Well, whatever you'd changed yesterday worked for me! Mostly. I made a couple tweaks to my config before it could run. Those being 1. Drop Gradient Ckpt Steps to 2 for the 1st dataset to get bucket'd. 2. Well, tried that again for the 2nd dataset, but it wasn't having it. May have been more an issue with cropping. I was first trying to maintain aspect ratio (nope), then use square with "face" crop (nope). Also tried to drop my Gradient Ckpt Steps to 1, no go. So I just sidelined it.

BTW, post-update, pre-gradient step change etc, I was receiving an error regarding there being 10 images but then there was a cache-split leaving 10 w/ 1 worker, 0 w/ another leading to the critical error of the bucket not locating any images. 

I'm not concerned, have too much crap open but oddly training crashed due to running out of memory. The odd part is it says its at 81GB of VRAM but I only have 64GB. Superbly high considering I'm only running a 5 image batch size. This is with or without u-net attention slice passed as an arg. 

If all fails, I'll see what happens with a vanilla/test run.

**Comment by bghira** [comment]
you might have to try something like:

```sh
kill $(ps auxw|grep -i simpletuner | awk '{ print $2; }')
```

to eliminate any zombie processes from a failed run.

this will typically clear up the vram in use

for bs=4 and aspect bucketed images, i'm seeing about 37-46gb of VRAM in use, depending on whether the VAE is being used during training.

you can try `--vae_cache_preprocess` which will go back to the former method of running the batched VAE encodes before training begins, which reduces VRAM use by a fair amount.

**Comment by bghira** [comment]
if dropping gradient accumulations fixed the issue, it's because your batch size was too high for the small # of images in the dataset

the dataset must have at least the `TRAIN_BATCH_SIZE * GRADIENT_ACCUMULATION_STEPS * NUM_GPU` number of images **in each bucket**

**Comment by BuildBackBuehler** [comment]
> if dropping gradient accumulations fixed the issue, it's because your batch size was too high for the small # of images in the dataset
> 
> the dataset must have at least the `TRAIN_BATCH_SIZE * GRADIENT_ACCUMULATION_STEPS * NUM_GPU` number of images **in each bucket**

Man, training SD LoRAs are the most convoluted -- my eyes had just glazed over when I'd originally read/seen that formula so of course it'd nip me in the butt. 

I'll give the --vae_cache_preprocess a try if things don't pan out. 

OT, can create another thread, but I'd love to have a new crop aspect option, `catch_all` or `best_fit`. The function parses a dataset for the image dimensions and splits them into 3 buckets based on portrait, landscape and square. Therein, whichever an aspect ratio comes closest to, it'll go into the P, L or S bucket. 

I figure the standards in SDXL of 1024x1024, 768x1344 and 1344x768 (or at least I think those were the top 3 dimensioned image sizes for the original SDXL checkpoint). I'm going to try my best to incorporate that and would put in a PR but don't hold your breath lol

**Comment by komninoschatzipapas** [comment]
@bghira 

I am also getting the same error:
```
Traceback (most recent call last):
  File "/workspace/SimpleTuner/train_sdxl.py", line 1633, in <module>
    main()
  File "/workspace/SimpleTuner/train_sdxl.py", line 838, in main
    unet, lr_scheduler, optimizer, train_dataloaders[0]
IndexError: list index out of range
```

When using this `sdxl-env.sh`:
```
...
export DATALOADER_CONFIG="/workspace/multidatabackend.json"
...
```

`/workspace/multidatabackend.json`:
```
[
  {
    "id": "orion",
    "dataset_type": "image",
    "type": "local",
    "instance_data_dir": "/workspace/combined",
    "crop": false,
    "caption_strategy": "textfile",
    "text_embeds": "alt-embed-cache"
  },
  {
    "id": "alt-embed-cache",
    "dataset_type": "text_embeds",
    "default": true,
    "type": "local",
    "model_type": "sdxl",
    "cache_dir": "/workspace/textembed_cache"
  }
]
```

Where `/workspace/combined` contains a list of JPEG files and their respective TXT caption files:
```
-rwxr-xr-x 1 root root  685355 Apr 10 18:47 ffcf0d3d-ce6b-4625-8ed1-adc11a7ded8b.jpg
-rw-r--r-- 1 root root     134 Apr 10 18:47 ffcf0d3d-ce6b-4625-8ed1-adc11a7ded8b.txt
-rwxr-xr-x 1 root root  922240 Apr 10 18:47 ffffde96-b485-48a2-b7fa-24066aafedd5.jpg
-rw-r--r-- 1 root root     193 Apr 10 18:47 ffffde96-b485-48a2-b7fa-24066aafedd5.txt
...
```

And `/workspace/textembed_cache` is an empty directory.

I am quite puzzled. I also looked at the code and, as @BuildBackBuehler noted, the `train_dataloaders` array should have at least one item as it's being built by iterating the array imported from `/workspace/multidatabackend.json`.

I am not sure what I'm missing.

**Comment by bghira** [comment]
you'll have to enable DEBUG log level (in sdxl-env.sh) and see what it says in `debug.log` for the `DataBackendFactory` log.

**Comment by komninoschatzipapas** [comment]
> you'll have to enable DEBUG log level (in sdxl-env.sh) and see what it says in `debug.log` for the `DataBackendFactory` log.

I tried with the following lines on my `sdxl-env.sh`:
```
export SIMPLETUNER_LOG_LEVEL=DEBUG
export SIMPLETUNER_TRAINING_LOOP_LOG_LEVEL=DEBUG
```

But did not get any more info than this:
```
2024-04-17 18:25:45,224 [INFO] (ArgsParser) VAE Model: madebyollin/sdxl-vae-fp16-fix
2024-04-17 18:25:45,224 [INFO] (ArgsParser) Default VAE Cache location: /workspace/output/cache_vae
2024-04-17 18:25:45,224 [INFO] (ArgsParser) Text Cache location: cache
2024-04-17 18:25:45,227 [WARNING] (accelerate.utils.other) Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
2024-04-17 18:25:45,230 [INFO] (__main__) Enabling tf32 precision boost for NVIDIA devices due to --allow_tf32.
2024-04-17 18:25:45,230 [INFO] (__main__) Load tokenizers
2024-04-17 18:25:46,277 [INFO] (__main__) Load text encoder 1..
2024-04-17 18:25:46,960 [INFO] (__main__) Load text encoder 2..
2024-04-17 18:25:48,831 [INFO] (__main__) Load VAE..
2024-04-17 18:25:49,022 [INFO] (__main__) Moving models to GPU. Almost there.
2024-04-17 18:25:51,174 [INFO] (__main__) Creating the U-net..
        2024-04-17 18:25:57,292 [INFO] (__main__) Moving the U-net to GPU in torch.bfloat16 precision.
2024-04-17 18:26:02,360 [INFO] (__main__) Enabling xformers memory-efficient attention.
2024-04-17 18:26:02,452 [INFO] (__main__) Initialising VAE in bf16 precision, you may specify a different value if preferred: bf16, fp32, default
2024-04-17 18:26:02,590 [INFO] (__main__) Loaded VAE into VRAM.
2024-04-17 18:26:02,621 [INFO] (DataBackendFactory) Configuring text embed backend: alt-embed-cache
2024-04-17 18:26:02,622 [INFO] (TextEmbeddingCache) (Rank: 0) (id=alt-embed-cache) Listing all text embed cache entries
2024-04-17 18:26:02,623 [INFO] (DataBackendFactory) Pre-computing null embedding for caption dropout
2024-04-17 18:26:02,624 [INFO] (DataBackendFactory) Completed loading text embed services.
2024-04-17 18:26:02,928 [INFO] (validation) Precomputing the negative prompt embed for validations.
2024-04-17 18:26:03,075 [INFO] (__main__) Unloading text encoders, as they are not being trained.
2024-04-17 18:26:03,278 [INFO] (__main__) After nuking text encoders from orbit, we freed 0.0 GB of VRAM. The real memories were the friends we trained a model on along the way.
2024-04-17 18:26:03,279 [INFO] (__main__) Collected the following data backends: ['alt-embed-cache']
2024-04-17 18:26:03,279 [INFO] (__main__) Loading polynomial learning rate scheduler with 1000 warmup steps
2024-04-17 18:26:03,285 [INFO] (__main__) Learning rate: 8e-07
2024-04-17 18:26:03,285 [INFO] (__main__) Using bf16 AdamW optimizer with stochastic rounding.
2024-04-17 18:26:03,286 [INFO] (__main__) Optimizer arguments, weight_decay=0.01 eps=1e-08, extra_arguments={'weight_decay': 0.01, 'eps': 1e-08, 'betas': (0.9, 0.999), 'lr': 8e-07}
2024-04-17 18:26:03,292 [INFO] (__main__) Using Polynomial learning rate scheduler.
2024-04-17 18:26:03,293 [INFO] (__main__) Loading our accelerator...
Traceback (most recent call last):
  File "/workspace/SimpleTuner/train_sdxl.py", line 1633, in <module>
    main()
  File "/workspace/SimpleTuner/train_sdxl.py", line 838, in main
    unet, lr_scheduler, optimizer, train_dataloaders[0]
IndexError: list index out of range
```

I also tried looking at my `output_dir`, but couldn't find any logs there either:
```
drwxr-xr-x 4 root root 135 Apr 17 18:26 .
drwxr-xr-x 1 root root 223 Apr 17 17:58 ..
-rw-r--r-- 1 root root   2 Apr 17 18:26 all_caption_files.json
-rw-r--r-- 1 root root 204 Apr 17 18:26 all_text_cache_files_alt-embed-cache.json
drwxr-xr-x 2 root root  10 Apr 17 14:42 cache
drwxr-xr-x 2 root root  10 Apr 17 14:42 cache_vae
```

Any help is appreciated.

**Comment by bghira** [comment]
debug.log is written in the same dir you execute the trainer from, usually the SimpleTuner top level directory

**Comment by bghira** [comment]
```
2024-04-17 18:26:03,279 [INFO] (__main__) Collected the following data backends: ['alt-embed-cache']
```

though i see it plainly stating there it didn't configure the other dataset 🤔

**Comment by bghira** [comment]
please try the latest master branch which has a resolution for this issue.

**Comment by komninoschatzipapas** [comment]
Thank you this works now
