### ISSUE TITLE
Unable to create Flux LoRA with quanto-int8

### ISSUE THREAD

**Issue by JohnTheNerd** [bghira/SimpleTuner#717]
I have been trying to finetune Flux for a little while now, however, I ran into a number of issues. In order to eliminate any potential issues with my environment, I also tested in both Docker (using the Dockerfile given, with a few minor modifications to drop into a shell and install `sentencepiece` which seems to be necessary, alongside the newer `diffusers` version and `optimum-quanto` as documented in the Flux guide) and directly from my local machine as directed by the documentation. Tested both `release` and `main` branches, for good measure.

If I use quanto-int8, the error I get is a lot like #644:

> Traceback (most recent call last):                                                                                            
  File "/workspace/SimpleTuner/train.py", line 2751, in <module>                                                              
    main()                                                                                                                    
  File "/workspace/SimpleTuner/train.py", line 1383, in main                                                                  
    results = accelerator.prepare(                                                                                            
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1299, in prepare           
    result = tuple(                                                                                                           
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1300, in <genexpr>         
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)                     
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1176, in _prepare_one      
    return self.prepare_model(obj, device_placement=device_placement)                                                         
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1435, in prepare_model     
    model = torch.nn.parallel.DistributedDataParallel(                                                                        
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 784, in __init__    
    self._log_and_throw(                                                                                                      
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1127, in _log_and_th
row
    raise err_type(err_msg)
RuntimeError: Modules with uninitialized parameters can't be used with `DistributedDataParallel`. Run a dummy forward pass to 
correctly initialize the modules

Disabling accelerate by adding `export SIMPLETUNER_DISABLE_ACCELERATOR=true` to the configuration lets me get past this step, but then I got:

> Traceback (most recent call last):
  File "/workspace/SimpleTuner/train.py", line 2751, in <module>
    main()
  File "/workspace/SimpleTuner/train.py", line 2179, in main
    model_pred = unpack_latents(
  File "/workspace/SimpleTuner/helpers/models/flux/__init__.py", line 32, in unpack_latents
    batch_size, num_patches, channels = latents.shape
ValueError: too many values to unpack (expected 3)

In order to make the error go away, I updated the respective line in flux/__init__.py to instead be `batch_size, num_patches, channels, _ = latents.shape` which then got slightly further and resulted in:

> Traceback (most recent call last):
  File "/workspace/SimpleTuner/train.py", line 2751, in <module>
    main()
  File "/workspace/SimpleTuner/train.py", line 2179, in main
    model_pred = unpack_latents(
  File "/workspace/SimpleTuner/helpers/models/flux/__init__.py", line 37, in unpack_latents
    latents = latents.view(batch_size, height, width, channels // 4, 2, 2)
RuntimeError: shape '[4, 64, 64, 32, 2, 2]' is invalid for input of size 1048576

If I do not use quanto-int8, it looks like it works but I cannot test much, it OOM's because I have 24GB VRAM. To note, unlike #644 I actually tried with multi-gpu support disabled, it won't work even with one of the GPUs. Furthermore, I also added `export CUDA_VISIBLE_DEVICES=0` to the configuration (and ran it in the shell) to make sure the second GPU is not visible at all to the training script.

**Comment by JohnTheNerd** [comment]
Interestingly, even disabling the GPU entirely did not seem to fix this issue. I followed the instructions given in [this Stack Exchange article](https://unix.stackexchange.com/questions/654075/how-can-i-disable-and-later-re-enable-one-of-my-nvidia-gpus) which made the second GPU disappear from `nvidia-smi`:
![image](https://github.com/user-attachments/assets/8960071b-769f-4ff7-be07-708e011c2bb4)

Yet the error still occurs:
![image](https://github.com/user-attachments/assets/edd21195-f161-4071-880a-4dfdc8334851)

How is it still aware that I have a second GPU? Is there a way to just force it to start training, even if the second GPU must remain idle?

**Comment by mhirki** [comment]
I don't have any experience with a multi-GPU system but you could try running `accelerate config`. When it asks you this question:
`What GPU(s) (by id) should be used for training on this machine as a comma-seperated list? [all]:`
You should answer either with "0" or "1". This should make it only use a specific GPU on your system.

**Comment by bghira** [comment]
the DISABLE_ACCELERATOR option is really for debugging non-training-loop related issues, eg. aspect bucketing, validations, save/load hooks and other elements of the trainer that still run when the model is doing nothing

currently quanto is a hard stop for multigpu training. this is a duplicate of #644 but if you're able, maybe implementing multigpu torchao quantisation sounds fun? :) that has a multigpu training example.

**Comment by JohnTheNerd** [comment]
Thanks @mhirki - that worked perfectly! Turns out the accelerate config is located in the huggingface cache directory, which I unwillingly mounted and re-used. At least I can train with a single GPU now.

I don't know a lot about the machine learning side of things, I'm still learning. My first attempt to fix the issue was to just do a forward pass with random tensors (as the error message hinted), hoping it at least initializes successfully, which I failed miserably to do as I didn't even know the shape to pass into torch.randn().

I do have a few very minor fixes unrelated to multi-gpu that I will upstream in a PR when I get a chance.
